### ISSUE TITLE
check ParameterFlags in GetSubscriberType

### ISSUE THREAD

**Issue by ProHolz** [viniciusfbb/ipub-messaging#2]
to be consistent between RTTI and manual subscribe there should be a check in GetSubscriberType
for manual subscription this declaration is used:
TipSubscriberMethod<T> = procedure(const AMessage: T) of object;
So please add this: (if LRttiParamType = nil then)

 ```
 if  not ( pfConst in LRttiMethod.GetParameters[0].Flags) then
       raise EipMessaging.CreateFmt('Method %s.%s have invalid parameter modifier. Should be const!', [AClass.QualifiedClassName, LRttiMethod.Name]);
```

Also add to the readme that you can subscribe to protected methods if you add:
 ` {$RTTI EXPLICIT METHODS([vcProtected, vcPublic, vcPublished])}`
before the class

**Comment by viniciusfbb** [comment]
Fixed
